//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoADatos.DaseDatosGS
{
    using Config;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class GeneralStore_Entities : DbContext
    {

        public GeneralStore_Entities()
            : base(ConectionDatabase.ConString)
        {
            
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bodega> Bodegas { get; set; }
        public virtual DbSet<Herramienta> Herramientas { get; set; }
        public virtual DbSet<Herramienta_Bodega> Herramienta_Bodega { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Item_Bodega> Item_Bodega { get; set; }
        public virtual DbSet<TasaCambio> TasaCambios { get; set; }
    }
}
